### PR TITLE
upgrade wlroots from 0.15.1 to 0.17.1

### PR DESCRIPTION
**Pull request by RyanGibb**

### CODE REVIEW

**Comment by Armael** [comment]
oh nice, thanks!
Btw, I'm not actively maintaining this library at the moment, so I'm happy to add you as a maintainer/give you commit rights, if that helps you hack on it.

**Comment by Armael** [comment]
(oops, wrong button)

**Comment by RyanGibb** [comment]
> oh nice, thanks!

No problem!

> Btw, I'm not actively maintaining this library at the moment, so I'm happy to add you as a maintainer/give you commit rights, if that helps you hack on it.

Sure! I've vendored this into my [downstream repo](https://github.com/RyanGibb/oway) for hacking on for the time being, but I'm hoping to spend more time on this and try and get something working.

**Comment by Armael** [comment]
Excellent! I'm curious to see what you come up with :-). In any case I've just added you as maintainer.

**Comment by RyanGibb** [comment]
Thanks @Armael !

**Pull request merged**
